### ISSUE TITLE
Menu Problem

### ISSUE THREAD

**Issue by upsidedowncan** [RickRollMaster101/fallguyloadrs6#2]
Hey RRM! There's an problem in your mod. If i try to open **any** menu, i **can't** switch on any other menus. Also when i **load** a map like that, the _**ui would just leave at the screen with the level.**_

**Comment by theatlasteam** [comment]
If you can, fix this problem!

**Comment by RRM101** [comment]
The UI being there has been fixed but I couldn't fix not being able to switch to the other menus

**Comment by RRM101** [comment]
Its fully fixed now

**Comment by theatlasteam** [comment]
alr
