### ISSUE TITLE
Settings don't change

### ISSUE THREAD

**Issue by upsidedowncan** [RickRollMaster101/fallguyloadrs6#7]
When i try to change settings (graphics cuz my pc is dead for sometime and im from laptop now) they are not changing. Also for me menus is changing only once, and then it dont change.

Uploading 2023-12-16_16-52-04.mp4…

**Comment by theatlasteam** [comment]
Uploading 2023-12-16_16-52-04.mp4…Uploading 2023-12-16_16-52-04.mp4…Uploading 2023-12-16_16-52-04.mp4…Uploading 2023-12-16_16-52-04.mp4…Uploading 2023-12-16_16-52-04.mp4…
